[package]
name = "portfolio"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
reqwest = { version = "0.12.18", features = ["json"] }
tera = "1.20.0"
tokio = { version = "1.45.1", features = ["full"] }
